language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install sphinx
script:
  - sphinx-build -b html docs/ docs/_build/html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/_build/html
  on:
    branch: main
